---
name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CI: true
  PACKAGES: 'language-hcl'
  VERSION: '1.7.10'

jobs:
  lint-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        channel: [stable]
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: UziTech/action-setup-atom@v2
      with:
        version: ${{ matrix.channel }}
    - name: atom version
      run: atom -v
    - name: apm version
      run: apm -v
    - name: install dependencies
      run: apm install && apm install ${PACKAGES} && apm clean
    - name: lint source and spec
      run: ./node_modules/.bin/eslint lib spec || true
    - name: install some pre-requisite packages
      run: sudo apt-get update && sudo apt-get -yq install curl xvfb libgbm-dev
    - name: install packer
      run: curl -o packer.zip https://releases.hashicorp.com/packer/${VERSION}/packer_${VERSION}_linux_amd64.zip && sudo unzip packer.zip -d /usr/bin/
    - name: run tests
      run: atom --test spec
